services:
  frontend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - internal
      - spa

  nginx:
    image: nginx:stable
    ports:
        - 80:80
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/logs:/var/log/nginx
        - ./nginx/app.conf.template:/etc/nginx/templates/app.conf.template:ro'
    networks:
        - internal
        - spa
    extra_hosts:
        - "host.docker.internal:host-gateway"

networks:
  internal:
    driver: bridge
  spa:
    external: true  